name: Build and Deploy NGINX Docker Image

on:
  push:
    branches: [ master ] 

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      
      - name: build
        run: GOOS=linux GOARCH=amd64 CGO_ENABLED=1 go build -o bin/packetbeat_linux_amd64 packetbeat/main.go