name: Build and Deploy NGINX Docker Image

on:
  push:
    branches: [ master ] 

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.21'  # 根据你的项目需求选择合适的Go版本

      - name: Get dependencies
        run: |
          go mod download
          go mod tidy
      
      - name: build
        run: GOOS=linux GOARCH=amd64 CGO_ENABLED=1 go build -o bin/packetbeat_linux_amd64 packetbeat/main.go